
CREATE TABLE IF NOT EXISTS Example (
    USER_ID INT NOT NULL,
    USERNAME VARCHAR(20) NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    PRIMARY KEY(USER_ID)
);

DROP TABLE Example;
SELECT * FROM Example;
SELECT * FROM users;