
CREATE TABLE IF NOT EXISTS Example (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(20) NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_DATE DATE NOT NULL
);
INSERT INTO Example(USERNAME, CREATED_BY, CREATED_DATE) VALUES('Fahad', 'Vaulsys', NOW());

DROP TABLE Example;
SELECT * FROM Example;
DELETE FROM Example;